### PR TITLE
Add Zypak

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by freeseacher** [comment]
As a result of integration of zypak like this every command made in shell is surrounded with 
image

also i've got dbus error on most launches. 

that is pretty annoying. i haven't found a solution for this and decided not to use it.

**Comment by refi64** [comment]
This PR is pretty much entirely broken, it's calling Zypak on the outermost wrapper script, meaning its hooks end up applying to bash *and* PyCharm itself (inc. the entire JVM) *and* the entire terminal and everything inside.

It should probably be attaching to `jcef_helper`, the actual Chromium-using binary in question...unfortunately, that does not seem to work, and I'm not sure why yet. Regardless, this should be reverted in the mean time and the update should just be rolled back.

**Comment by refi64** [comment]
Filed https://github.com/refi64/zypak/issues/31 to figure out how to make this work.

**Comment by refi64** [comment]
Well this is *significantly* uglier than I expected to work around... In the mean time, for the record, [the goland PR](https://github.com/flathub/com.jetbrains.GoLand/pull/67) just disables the jcef sandboxing, which is a much better workaround for now.

**Pull request merged**
